name: Build and Deploy Website
on: ["push", "pull_request"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build the page
        run: |
          # Jekyll offers no option for non-zero exit codes on parse errors
          # c.f. https://github.com/jekyll/jekyll/issues/5257
          [ ! $(bundle exec jekyll build | tee /dev/stderr | grep 'Error: YAML Exception') ]

      - name: Push to GH Pages
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: _site
